# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: false
dist: trusty


before_install:
  - svn checkout https://projects.coin-or.org/svn/Cbc/releases/2.9.8 Cbc-2.9.8
  - cd Cbc-2.9.8
  - ./configure
  - make
  - make install
  - cd ..

install:
  - Rscript -e 'install.packages("clpAPI", configure.args = list(PKG_CPPFLAGS = "/home/travis/build/rte-antares-rpackage/testTravisForR/SYMPHONY-5.6"))'
