# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: false
dist: trusty


before_install:
  - LD_LIBRARY_PATH=/usr/local/lib
  - LD_RUN_PATH=/usr/local/lib
  - PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

#
#  - svn checkout https://projects.coin-or.org/svn/Clp/stable/1.16 coin-Clp
#  - cd coin-Clp
#  - ./configure
#  - make
#  - make install
#  - export PATH=$PATH:/home/travis/build/rte-antares-rpackage/coin-Clp
#  - export PATH=$PATH:/home/travis/build/rte-antares-rpackage/coin-Clp/include
#  - export PATH=$PATH:/home/travis/build/rte-antares-rpackage/coin-Clp/include/coin
#  - cd ..
#
install:
  - Rscript -e 'install.packages("clpAPI")'
