# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages


 env:
  - NB='w/ foreach' ## Just a label
  - _R_CHECK_TESTSETS_=foreach
  - _R_CHECK_FUTURE_STRATEGIES_=sequential,multicore,multisession,batchjobs_local,batchtools_local
